import Navbar from '../../componentsShared/Navbar'
import '../../public/globals.css'
import { Poppins } from 'next/font/google'
//@t
const poppins = Poppins( {
  subsets: ['latin'],
  weight:['300','500','700']
} )

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        </body>
    </html>
  )
}
